<?php

namespace Lacces\LaccesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * logoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logoRepository extends EntityRepository
{
}
