<?php

namespace Lacces\LaccesBundle\Repository;

/**
 * traductionFrEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traductionFrEnRepository extends \Doctrine\ORM\EntityRepository
{
}
