<?php

namespace Lacces\LaccesBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * wordEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traductionFrEnRepository extends EntityRepository
{

  public function findByIds($idFr, $idEn) {
    return $this->createQueryBuilder('c')
      ->where('c.word_fr = :word_fr')
      ->andWhere('c.word_en = :word_en')
      ->setParameters(array(
        'word_en' => $idEn,
        'word_fr' => $idFr
      ))
      ->getQuery()
      ->getOneOrNullResult();

  }
}
