<?php

namespace Lacces\LaccesBundle\Repository;

/**
 * traductionFrEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traductionFrEnRepository extends \Doctrine\ORM\EntityRepository
{
  public function findIdFrByIdEn($id){
    return $this->createQueryBuilder('c')
    ->select('c.idFr')
    ->where('c.idEn = :en')
    ->setParameter('en', $id)
    ->getQuery()
    ->getOneOrNullResult();
  }

  public function findIdEnByIdFr($id){
    return $this->createQueryBuilder('c')
    ->select('c.idEn')
    ->where('c.idFr = :fr')
    ->setParameter('fr', $id)
    ->getQuery()
    ->getOneOrNullResult();
  }
}
