<?php

namespace Lacces\LaccesBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * wordFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wordFrRepository extends EntityRepository
{
  public function findByWord($w){
    try {
      return $this->createQueryBuilder('c')
        ->where('c.word = :word')
        ->setParameter('word', $w)
        ->leftJoin('c.wordEns', 'b')
        ->addSelect('b')
        ->getQuery()
        ->getOneOrNullResult();
    } catch (NonUniqueResultException $e) {
    }
  }

  public function findByPopularity (){
    return $this->createQueryBuilder('c')
        ->select('c.word')
        ->orderBy('c.popularity', 'DESC')
        ->addOrderBy('c.word', 'ASC')
        ->getQuery()
        ->getResult();
  }

  public function findAll(){
    return $this->createQueryBuilder('c')
    ->orderBy('c.word', 'ASC')
    ->getQuery()
    ->getResult();
  }

  public function findAlea() {

    return  $this->createQueryBuilder('c')
      ->addSelect('RAND() as HIDDEN rand')
      ->addOrderBy('rand')
      ->getQuery()
      ->getResult();

  }
}
