<?php

namespace Lacces\LaccesBundle\Repository;

/**
 * wordEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wordEnRepository extends \Doctrine\ORM\EntityRepository
{
}
