insert into word_fr (word, videoLink, contextSentence, popularity) values("père", "fdgdfg", "C'est mon père !", 9);
insert into word_fr (word, videoLink, contextSentence, popularity) values("mot", "fdgdfg", "Une phrase est construite avec des mots", 8);
insert into word_fr (word, videoLink, contextSentence, popularity) values("oui", "fdgdfg", "je vous repond oui !", 42);
insert into word_fr (word, videoLink, contextSentence, popularity) values("manger", "fdgdfg", "j'adore manger", 823);
insert into word_fr (word, videoLink, contextSentence, popularity) values("vendre", "fdgdfg", "Je vend ma maison", 12);
insert into word_fr (word, videoLink, contextSentence, popularity) values("Terre", "fdgdfg", "La Terre est ronde", 38);
insert into word_fr (word, videoLink, contextSentence, popularity) values("souris", "fdgdfg", "Une souris verte", 28);
insert into word_fr (word, videoLink, contextSentence, popularity) values("canard", "fdgdfg", "Un canard jaune", 82);
insert into word_fr (word, videoLink, contextSentence, popularity) values("envoyer", "fdgdfg", "envoyer un cadeau", 1);
insert into word_fr (word, videoLink, contextSentence, popularity) values("tirer", "fdgdfg", "tirer sur des cibles", 10);
insert into word_fr (word, videoLink, contextSentence, popularity) values("non", "fdgdfg", "Non, je ne suis pas d'accord", 10);
insert into word_fr (word, videoLink, contextSentence, popularity) values("bonjour", "fdgdfg", "Boujour la France !", 10);
insert into word_fr (word, videoLink, contextSentence, popularity) values("bonsoir", "fdgdfg", "Bonsoir la France !", 10);
insert into word_fr (word, videoLink, contextSentence, popularity) values("montrer", "fdgdfg", "Je vais vous montrer", 10);
insert into word_fr (word, videoLink, contextSentence, popularity) values("ouvrir", "fdgdfg", "Peux-tu ouvrir la porte s'il te plaît ?", 10);
insert into word_fr (word, videoLink, contextSentence, popularity) values("fermer", "fdgdfg", "Peux-tu fermer la porte s'il te plaît ?", 10);
insert into word_fr (word, videoLink, contextSentence, popularity) values("crayon", "fdgdfg", "J'ai un crayon", 10);
insert into word_fr (word, videoLink, contextSentence, popularity) values("règle", "fdgdfg", "Il y a des règles à respecter", 10);

insert into word_en (word, videoLink, contextSentence, popularity) values("father", "fdgdfg", "It's my father !", 2);
insert into word_en (word, videoLink, contextSentence, popularity) values("word", "fdgdfg", "A sentence is built with words", 58);
insert into word_en (word, videoLink, contextSentence, popularity) values("yes", "fdgdfg", "I answer you yes !", 22);
insert into word_en (word, videoLink, contextSentence, popularity) values("eat", "fdgdfg", "I love eat", 23);
insert into word_en (word, videoLink, contextSentence, popularity) values("sell", "fdgdfg", "I sale my house", 12);
insert into word_en (word, videoLink, contextSentence, popularity) values("earth", "fdgdfg", "Earth is round", 8);
insert into word_en (word, videoLink, contextSentence, popularity) values("mouse", "fdgdfg", "a green mouse", 8);
insert into word_en (word, videoLink, contextSentence, popularity) values("duck", "fdgdfg", "a yellow duck", 2);
insert into word_en (word, videoLink, contextSentence, popularity) values("send", "fdgdfg", "to send a gift", 81);
insert into word_en (word, videoLink, contextSentence, popularity) values("shoot", "fdgdfg", "to shoot on target", 0);
insert into word_en (word, videoLink, contextSentence, popularity) values("no", "fdgdfg", "No I don't agree", 10);
insert into word_en (word, videoLink, contextSentence, popularity) values("good morning", "fdgdfg", "Good morning France !", 10);
insert into word_en (word, videoLink, contextSentence, popularity) values("good afternoon", "fdgdfg", "Good afternoon France !", 10);
insert into word_en (word, videoLink, contextSentence, popularity) values("show", "fdgdfg", "I will show you", 10);
insert into word_en (word, videoLink, contextSentence, popularity) values("open", "fdgdfg", "Can you open the door please ?", 10);
insert into word_en (word, videoLink, contextSentence, popularity) values("close", "fdgdfg", "Can you close the door please ?", 10);
insert into word_en (word, videoLink, contextSentence, popularity) values("pencil", "fdgdfg", "I have a pencil", 10);
insert into word_en (word, videoLink, contextSentence, popularity) values("rule", "fdgdfg", "There are rules to respect", 10);

insert into traductionfren (word_fr_id, word_en_id) values(1, 1);
insert into traductionfren (word_fr_id, word_en_id) values(2, 2);
insert into traductionfren (word_fr_id, word_en_id) values(3, 3);
insert into traductionfren (word_fr_id, word_en_id) values(4, 4);
insert into traductionfren (word_fr_id, word_en_id) values(5, 5);
insert into traductionfren (word_fr_id, word_en_id) values(6, 6);
insert into traductionfren (word_fr_id, word_en_id) values(7, 7);
insert into traductionfren (word_fr_id, word_en_id) values(8, 8);
insert into traductionfren (word_fr_id, word_en_id) values(9, 9);
insert into traductionfren (word_fr_id, word_en_id) values(10, 10);
insert into traductionfren (word_fr_id, word_en_id) values(11, 11);
insert into traductionfren (word_fr_id, word_en_id) values(12, 12);
insert into traductionfren (word_fr_id, word_en_id) values(13, 13);
insert into traductionfren (word_fr_id, word_en_id) values(14, 14);
insert into traductionfren (word_fr_id, word_en_id) values(15, 15);
insert into traductionfren (word_fr_id, word_en_id) values(16, 16);
insert into traductionfren (word_fr_id, word_en_id) values(17, 17);
insert into traductionfren (word_fr_id, word_en_id) values(18, 18);