lacces_homepage:
    path:     /
    defaults:
        _controller: LaccesBundle:Default:index

lacces_signeur_fr:
    path:     /signaire/Fr
    defaults:
        _controller: LaccesBundle:Default:signaireFr

lacces_signeur_en:
    path:     /signaire/En
    defaults:
        _controller: LaccesBundle:Default:signaireEn

lacces_word:
    path:     /word/{langue}/{word}
    defaults:
        _controller: LaccesBundle:Default:word
