lacces_homepage:
    path:     /
    defaults:
        _controller: LaccesBundle:Default:index

lacces_signaire_fr:
    path:     /signaire/Fr
    defaults:
        _controller: LaccesBundle:Default:signaireFr

lacces_signaire_en:
    path:     /signaire/En
    defaults:
        _controller: LaccesBundle:Default:signaireEn

lacces_word:
    path:     /word/{langue}/{word}
    defaults:
        _controller: LaccesBundle:Default:word
    requirements:
      langue: en|fr

lacces_contact:
    path:     /contact
    defaults:
        _controller: LaccesBundle:Default:contact

lacces_mentions_legales:
    path:     /mentions_legales
    defaults:
        _controller: LaccesBundle:Default:mentions

lacces_faq:
    path:     /faq
    defaults:
        _controller: LaccesBundle:Default:faq

