lacces_homepage:
    path:     /
    defaults:
        _controller: LaccesBundle:Default:index

lacces_signaire_fr:
    path:     /signaire/Fr
    defaults:
        _controller: LaccesBundle:Default:signaireFr

lacces_signaire_en:
    path:     /signaire/En
    defaults:
        _controller: LaccesBundle:Default:signaireEn

lacces_word:
    path:     /word/{langue}/{word}
    defaults:
        _controller: LaccesBundle:Default:word
    requirements:
      langue: en|fr

lacces_contact:
    path:     /contact
    defaults:
        _controller: LaccesBundle:Contact:contact

lacces_mentions_legales:
    path:     /mentions_legales
    defaults:
        _controller: LaccesBundle:Default:mentions

lacces_faq:
    path:     /faq
    defaults:
        _controller: LaccesBundle:Default:faq

auto_complete:
    path:   /search
    defaults:
        _controller: LaccesBundle:Default:autoComplete

lacces_editData_edit:
    path: /administration/editData/edit/{wordId}/{langue}
    defaults:
        _controller: LaccesBundle:EditDataWord:edit
    requirements:
        wordFrId: /d+
        wordEnId: /d+

lacces_editData_add:
    path: /administration/editData/add
    defaults:
        _controller: LaccesBundle:EditDataWord:add

lacces_editData_remove:
    path: /administration/editData/remove
    defaults:
        _controller: LaccesBundle:EditDataWord:remove

lacces_wordList:
    path: /administration/editData/wordList/{langue}
    defaults:
        _controller: LaccesBundle:EditDataWord:wordList
    requirements:
        langue: fr|en

adminLogin:
    path: /adminLogin
    defaults:
        _controller: LaccesBundle:Security:adminLogin

login_check:
    path: /login_check
    defaults:
        _controller: LaccesBundle:Security:loginCheck

logout:
    path: /logout
    defaults:
        _controller: LaccesBundle:Security:logout

administration:
    path: /administration
    defaults:
        _controller: LaccesBundle:EditDataWord:admin

lacces_exercices:
    path:   /exercices/{langue}
    defaults:
        _controller: LaccesBundle:Exercice:exercices

lacces_ex__fr_add:
    path: /administration/exerciceFr/add
    defaults:
        _controller: LaccesBundle:EditDataExercice:exerciceAddFr

lacces_ex__en_add:
    path: /administration/exerciceEn/add
    defaults:
        _controller: LaccesBundle:EditDataExercice:exerciceAddEn