lacces_homepage:
    path:     /
    defaults:
        _controller: LaccesBundle:Default:index

lacces_signaire_fr:
    path:     /signaire/Fr
    defaults:
        _controller: LaccesBundle:Default:signaireFr

lacces_signaire_en:
    path:     /signaire/En
    defaults:
        _controller: LaccesBundle:Default:signaireEn

lacces_word:
    path:     /word/{langue}/{word}
    defaults:
        _controller: LaccesBundle:Default:word
    requirements:
      langue: en|fr

lacces_contact:
    path:     /contact
    defaults:
        _controller: LaccesBundle:Contact:contact

lacces_mentions_legales:
    path:     /mentions_legales
    defaults:
        _controller: LaccesBundle:Default:mentions

lacces_faq:
    path:     /faq
    defaults:
        _controller: LaccesBundle:Default:faq

auto_complete:
    path:   /search
    defaults:
        _controller: LaccesBundle:Default:autoComplete

lacces_exercices:
    path:   /exercices
    defaults:
        _controller: LaccesBundle:Default:exercices

lacces_editData_edit:
    path: /editData/edit/{wordId}/{langue}
    defaults:
        _controller: LaccesBundle:EditData:edit
    requirements:
        wordFrId: /d+
        wordEnId: /d+

lacces_editData_add:
    path: /editData/add
    defaults:
        _controller: LaccesBundle:EditData:add

lacces_editData_remove:
    path: /editData/remove
    defaults:
        _controller: LaccesBundle:EditData:remove

lacces_wordList:
    path: /editData/wordList/{langue}
    defaults:
        _controller: LaccesBundle:EditData:wordList
    requirements:
        langue: fr|en

adminLogin:
    path: /admin
    defaults:
        _controller: LaccesBundle:Security:admin

login_check:
    path: /login_check
    defaults:
        _controller: LaccesBundle:Security:loginCheck

logout:
    path: /logout
    defaults:
        _controller: LaccesBundle:Security:logout