<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * comparaisonVideoEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comparaisonVideoEnRepository extends \Doctrine\ORM\EntityRepository
{
}
