<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * qcm_video_enRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qcm_video_enRepository extends \Doctrine\ORM\EntityRepository
{
}
