<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * qcmEnonceFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qcmEnonceFrRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByQcmFrId ($qcmFrId){
    return $this->createQueryBuilder('c')
      ->select('c.id')
      ->where('c.qcmFr=:word')
      ->setParameter('word', $qcmFrId)
      ->getQuery()
      ->getResult();
  }
}
