<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * qcmEnonceVideoFrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qcmEnonceVideoFrRepository extends \Doctrine\ORM\EntityRepository
{
}
