<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * qcmEnonceVideoEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qcmEnonceVideoEnRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByQcmVideoEnId ($qcmVideoEnId){
    return $this->createQueryBuilder('c')
      ->where('c.qcmVideoEn=:word')
      ->setParameter('word', $qcmVideoEnId)
      ->getQuery()
      ->getResult();
  }

    public function findQcmenonceByQcmAndEnonce($enonce){
        return $this->createQueryBuilder('c')
            ->where('c.enonces=:enonce')
            ->setParameter('enonce', $enonce)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
