<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * qcmEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qcmEnRepository extends \Doctrine\ORM\EntityRepository
{
}
