<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * qcmEnonceEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qcmEnonceEnRepository extends \Doctrine\ORM\EntityRepository
{
}
