<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * qcmEnonceEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qcmEnonceEnRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByQcmEnId ($qcmEnId){
    return $this->createQueryBuilder('c')
      ->select('c.id')
      ->where('c.qcmEn=:word')
      ->setParameter('word', $qcmEnId)
      ->getQuery()
      ->getResult();
  }
}
