<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * reformulationEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reformulationEnRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByWordEnId ($wordEnId){
    return $this->createQueryBuilder('c')
      ->select('c.id')
      ->where('c.wordEn=:word')
      ->setParameter('word', $wordEnId)
      ->getQuery()
      ->getResult();
  }
}
