<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * signification_video_enRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class signification_video_enRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByWordEn ($wordEnId){
    return $this->createQueryBuilder('c')
      ->select('c.id')
      ->where('c.wordEn=:word')
      ->setParameter('word', $wordEnId)
      ->getQuery()
      ->getResult();
  }
}
