<?php

namespace Lacces\LaccesBundle\Repository\Exercise;

/**
 * significationVideoEnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class significationVideoEnRepository extends \Doctrine\ORM\EntityRepository
{
}
